language: r
sudo: required

r_packages:
    - foreach
    - roxygen2

r_github_packages:
    - hadley/staticdocs

after_success:
    - if [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "$TRAVIS_PULL_REQUEST" == false ]]; then
        sh ./inst/deploy.sh;
      fi

notifications:
    email: false
