language: r
sudo: required

before_install: sudo apt-get install libgmp3-dev

after_success:
    - if [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "$TRAVIS_PULL_REQUEST" == false ]]; then
        sh deploy.sh;
      fi

notifications:
    email: false
