language: r
sudo: required

env:
    global:
    - secure: "EF9P0qhKbGVsnxGe/XTqCA4Pa/v9w1wCe4yQikDCHG8kUT22/BxEVJj8b5hRPE0UL/Iww/MPI5rIDEhlZHmVIQgosrx4kd9Y40oSHyJkL2iutEOnEXHjOMq71W0gjhJHdryWK3KvthJdtHvrgiM77I/7nYT71m3c3/pc4SX2dS4="

r_github_packages:
    - hadley/staticdocs

after_success:
    - sh inst/deploy.sh || exit 1

notifications:
    email: false
